-- Seed data migrated from races_backup.json (Railway CSV backup as of 2026-07-04).
-- Safe to re-run: uses INSERT OR IGNORE keyed on id.
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1782828308833', 'Formula 1', 'Italy (Monza)', 'Ferrari F1 24', 'Dry - Day', 'Harish', 'Harish', '1:22:213', '2026-06-10', 19, NULL, NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1782924245546', 'Auto Mobilista 2', 'Donington Park (UK)', 'Mini', 'Dry - Day', 'Harish', 'Harish', '1:36:060', '2026-07-01', 5, '08:19', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1782925651584', 'Auto Mobilista 2', 'Watkins Glen (USA)', 'Mini GT', 'Dry - Day', 'Harish', 'Shabesh', '1:59:460', '2026-07-01', 10, '20:20.794', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783009069686', 'Auto Mobilista 2', 'Road America (USA)', 'Gt3r', 'Dry - Day', 'Shabesh', 'Shabesh', '2:06.584', '2026-07-02', 10, '21:31.754', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783014398927', 'Auto Mobilista 2', 'Road America (USA)', 'GT4', 'Dry - Day', 'Harish', 'Harish', '1:31.5', '2026-07-02', 10, NULL, NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783014795656', 'Auto Mobilista 2', 'Spa-Francorchamps (Belgium)', 'GT4', 'Dry - Day', 'Harish', 'Harish', '1:53', '2026-07-02', 10, NULL, NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783015869952', 'Auto Mobilista 2', 'Spa-Francorchamps (Belgium)', 'GT4', 'Dry - Day', 'Harish', 'Harish', '2:32:701', '2026-07-02', 10, NULL, NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783156387155', 'Auto Mobilista 2', 'Brands Hatch (UK)', 'GT3', 'Dry - Day', 'Harish', 'Harish', '2:13.474', '2026-07-04', 10, NULL, NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783158725787', 'Auto Mobilista 2', 'Brands Hatch (UK)', 'Benz 190e', 'Dry - Day', 'Shabesh', 'Shabesh', '1:36.835', '2026-07-04', 10, NULL, NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783166866999', 'Auto Mobilista 2', 'Imola (Italy)', 'GT4', 'Dry - Day', 'Harish', 'Harish', '1:46.821', '2026-07-04', 6, NULL, NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783168282690', 'Formula 1', 'Italy (Imola)', 'Gt3 evo gen2', 'Dry - Day', 'Shabesh', 'Shabesh', '1:46:621', '2026-07-04', 10, NULL, NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783169686551', 'Auto Mobilista 2', 'Hockenheimring (Germany)', 'Gt3 amg', 'Dry - Day', 'Shabesh', 'Shabesh', '1:42.001', '2026-07-04', 4, NULL, NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO races (id, game, track, car_class, conditions, winner, fastest_lap, fastest_lap_time, date, laps, race_duration, harish_finishing_pos, shabesh_finishing_pos, harish_starting_pos, shabesh_starting_pos) VALUES ('race_1783172093266', 'Auto Mobilista 2', 'Hockenheimring (Germany)', 'GT3', 'Dry - Day', 'Harish', 'Shabesh', '1:41.548', '2026-07-04', 10, NULL, NULL, NULL, NULL, NULL);
